# Generated by Django 3.2.23 on 2024-01-30 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('face_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='img/face/%Y/%m/%d/', verbose_name='Фотография лица')),
            ],
            options={
                'verbose_name': 'Данные пользователей',
                'verbose_name_plural': 'Данные пользователей',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='date_user',
        ),
        migrations.AddField(
            model_name='data_user',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
